layout_spectrum: 0.9123103
typography_spectrum: 0.7259697
color:
  lightness: 1
  brandStrength: 0
  saturation: 0.6096122
  rhythmicContrast: 0.4409781
  brandColors:
    - '#91928D'
    - '#101010'
    - '#474738'
    - '#BA417B'
    - '#FE9478'
name: Sparkle Maltese
